@echo off
echo Stopping server...
pm2 stop your-app-name || exit /b 0  # Replace with your actual app name

echo Pulling latest code...
git pull origin main  # Ensure you're on the right branch

echo Installing dependencies...
npm install --production  # Install production dependencies

echo Starting server...
pm2 start your-app-name || npm start  # Replace with your actual start command
